
// Generated by Cadence Genus(TM) Synthesis Solution 20.10-p001_1
// Generated on: Nov 20 2025 14:10:34 IST (Nov 20 2025 08:40:34 UTC)

// Verification Directory fv/Faulty_EVM 

module Faulty_EVM(clk, reset, A_Push, B_Push, C_Push, ballot_signal,
     show_result, A_Led, B_Led, C_Led, buzzer_output, limit_exceeded,
     A_Count, B_Count, C_Count);
  input clk, reset, A_Push, B_Push, C_Push, ballot_signal, show_result;
  output A_Led, B_Led, C_Led, buzzer_output, limit_exceeded;
  output [7:0] A_Count, B_Count, C_Count;
  wire clk, reset, A_Push, B_Push, C_Push, ballot_signal, show_result;
  wire A_Led, B_Led, C_Led, buzzer_output, limit_exceeded;
  wire [7:0] A_Count, B_Count, C_Count;
  wire [7:0] A_Vote;
  wire [7:0] C_Vote;
  wire [7:0] B_Vote;
  wire [7:0] vote_count;
  wire [1:0] state;
  wire [1:0] buzzer_count;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_57, n_58, n_59, n_60, n_61, n_62, n_63;
  wire n_64, n_65, n_66, n_67, n_68, n_69, n_70, n_71;
  wire n_72, n_73, n_74, n_75, n_76, n_77, n_78, n_79;
  wire n_80, n_81, n_82, n_83, n_84, n_85, n_86, n_87;
  wire n_88, n_89, n_90, n_91, n_92, n_93, n_94, n_95;
  wire n_96, n_97, n_98, n_99, n_100, n_101, n_102, n_103;
  wire n_104, n_105, n_106, n_107, n_108, n_109, n_110, n_111;
  wire n_112, n_114, n_115, n_116, n_117, n_118, n_119, n_120;
  wire n_121, n_122, n_123, n_124, n_125, n_126, n_127, n_128;
  wire n_129, n_130, n_131, n_132, n_133, n_134, n_135, n_136;
  wire n_137, n_138, n_139, n_140, n_141, n_142, n_143, n_144;
  wire n_145, n_146, n_147, n_148, n_149, n_150, n_151, n_152;
  wire n_153, n_161, voted;
  assign C_Led = C_Push;
  assign B_Led = B_Push;
  assign A_Led = A_Push;
  SDFFRHQX1 \A_Vote_reg[7] (.RN (n_153), .CK (clk), .D (n_144), .SI
       (A_Vote[7]), .SE (n_150), .Q (A_Vote[7]));
  SDFFRHQX1 \C_Vote_reg[7] (.RN (n_153), .CK (clk), .D (C_Vote[7]), .SI
       (n_139), .SE (n_145), .Q (C_Vote[7]));
  SDFFRHQX1 \B_Vote_reg[7] (.RN (n_153), .CK (clk), .D (n_141), .SI
       (B_Vote[7]), .SE (n_148), .Q (B_Vote[7]));
  DFFRHQX1 \A_Vote_reg[6] (.RN (n_153), .CK (clk), .D (n_151), .Q
       (A_Vote[6]));
  DFFRHQX1 \C_Vote_reg[6] (.RN (n_153), .CK (clk), .D (n_152), .Q
       (C_Vote[6]));
  DFFRHQX1 \B_Vote_reg[6] (.RN (n_153), .CK (clk), .D (n_149), .Q
       (B_Vote[6]));
  OAI2BB1X1 g2993__2398(.A0N (C_Vote[6]), .A1N (n_133), .B0 (n_146), .Y
       (n_152));
  OAI2BB1X1 g2994__5107(.A0N (A_Vote[6]), .A1N (n_150), .B0 (n_143), .Y
       (n_151));
  OAI2BB1X1 g2995__6260(.A0N (B_Vote[6]), .A1N (n_148), .B0 (n_147), .Y
       (n_149));
  DFFRHQX1 \A_Vote_reg[3] (.RN (n_153), .CK (clk), .D (n_124), .Q
       (A_Vote[3]));
  DFFRHQX1 \C_Vote_reg[5] (.RN (n_153), .CK (clk), .D (n_130), .Q
       (C_Vote[5]));
  DFFRHQX1 \B_Vote_reg[5] (.RN (n_153), .CK (clk), .D (n_127), .Q
       (B_Vote[5]));
  DFFRHQX1 \A_Vote_reg[4] (.RN (n_153), .CK (clk), .D (n_136), .Q
       (A_Vote[4]));
  DFFRHQX1 \C_Vote_reg[4] (.RN (n_153), .CK (clk), .D (n_134), .Q
       (C_Vote[4]));
  DFFRHQX1 \B_Vote_reg[4] (.RN (n_153), .CK (clk), .D (n_135), .Q
       (B_Vote[4]));
  DFFRHQX1 \A_Vote_reg[5] (.RN (n_153), .CK (clk), .D (n_137), .Q
       (A_Vote[5]));
  DFFRHQX1 \B_Vote_reg[1] (.RN (n_153), .CK (clk), .D (n_128), .Q
       (B_Vote[1]));
  DFFRHQX1 \B_Vote_reg[3] (.RN (n_153), .CK (clk), .D (n_122), .Q
       (B_Vote[3]));
  DFFRHQX1 \C_Vote_reg[2] (.RN (n_153), .CK (clk), .D (n_132), .Q
       (C_Vote[2]));
  DFFRHQX1 \C_Vote_reg[1] (.RN (n_153), .CK (clk), .D (n_131), .Q
       (C_Vote[1]));
  DFFRHQX1 \C_Vote_reg[3] (.RN (n_153), .CK (clk), .D (n_123), .Q
       (C_Vote[3]));
  DFFRHQX1 \B_Vote_reg[2] (.RN (n_153), .CK (clk), .D (n_125), .Q
       (B_Vote[2]));
  DFFRHQX1 \A_Vote_reg[2] (.RN (n_153), .CK (clk), .D (n_126), .Q
       (A_Vote[2]));
  DFFRHQX1 \A_Vote_reg[1] (.RN (n_153), .CK (clk), .D (n_129), .Q
       (A_Vote[1]));
  OAI211X1 g3000__4319(.A0 (B_Vote[6]), .A1 (n_100), .B0 (n_140), .C0
       (n_119), .Y (n_147));
  OAI211X1 g3001__8428(.A0 (C_Vote[6]), .A1 (n_109), .B0 (n_138), .C0
       (n_145), .Y (n_146));
  XNOR2X1 g2996__5526(.A (A_Vote[7]), .B (n_142), .Y (n_144));
  OAI211X1 g2999__6783(.A0 (A_Vote[6]), .A1 (n_108), .B0 (n_142), .C0
       (n_120), .Y (n_143));
  XNOR2X1 g2998__3680(.A (B_Vote[7]), .B (n_140), .Y (n_141));
  XNOR2X1 g2997__1617(.A (C_Vote[7]), .B (n_138), .Y (n_139));
  SDFFRHQX1 \vote_count_reg[7] (.RN (n_153), .CK (clk), .D
       (vote_count[7]), .SI (n_95), .SE (n_121), .Q (vote_count[7]));
  OAI2BB1X1 g3006__2802(.A0N (A_Vote[5]), .A1N (n_150), .B0 (n_103), .Y
       (n_137));
  OAI2BB1X1 g3021__1705(.A0N (A_Vote[4]), .A1N (n_150), .B0 (n_115), .Y
       (n_136));
  OAI2BB1X1 g3022__5122(.A0N (B_Vote[4]), .A1N (n_148), .B0 (n_114), .Y
       (n_135));
  OAI2BB1X1 g3020__8246(.A0N (C_Vote[4]), .A1N (n_133), .B0 (n_118), .Y
       (n_134));
  OAI2BB1X1 g3059__7098(.A0N (C_Vote[2]), .A1N (n_133), .B0 (n_110), .Y
       (n_132));
  OAI2BB1X1 g3062__6131(.A0N (C_Vote[1]), .A1N (n_133), .B0 (n_111), .Y
       (n_131));
  OAI2BB1X1 g3005__1881(.A0N (C_Vote[5]), .A1N (n_133), .B0 (n_105), .Y
       (n_130));
  OAI2BB1X1 g3071__5115(.A0N (A_Vote[1]), .A1N (n_150), .B0 (n_102), .Y
       (n_129));
  SDFFRHQX1 \C_Vote_reg[0] (.RN (n_153), .CK (clk), .D (n_145), .SI
       (n_133), .SE (C_Vote[0]), .Q (C_Vote[0]));
  OAI2BB1X1 g3072__7482(.A0N (B_Vote[1]), .A1N (n_148), .B0 (n_106), .Y
       (n_128));
  OAI2BB1X1 g3007__4733(.A0N (B_Vote[5]), .A1N (n_148), .B0 (n_101), .Y
       (n_127));
  OAI2BB1X1 g3076__6161(.A0N (A_Vote[2]), .A1N (n_150), .B0 (n_107), .Y
       (n_126));
  OAI2BB1X1 g3077__9315(.A0N (B_Vote[2]), .A1N (n_148), .B0 (n_104), .Y
       (n_125));
  OAI2BB1X1 g3042__9945(.A0N (A_Vote[3]), .A1N (n_150), .B0 (n_116), .Y
       (n_124));
  OAI2BB1X1 g3043__2883(.A0N (C_Vote[3]), .A1N (n_133), .B0 (n_112), .Y
       (n_123));
  OAI2BB1X1 g3044__2346(.A0N (B_Vote[3]), .A1N (n_148), .B0 (n_117), .Y
       (n_122));
  SDFFRHQX1 \vote_count_reg[5] (.RN (n_153), .CK (clk), .D
       (vote_count[5]), .SI (n_91), .SE (n_121), .Q (vote_count[5]));
  SDFFRHQX1 \vote_count_reg[3] (.RN (n_153), .CK (clk), .D
       (vote_count[3]), .SI (n_89), .SE (n_121), .Q (vote_count[3]));
  SDFFRHQX1 \A_Vote_reg[0] (.RN (n_153), .CK (clk), .D (n_120), .SI
       (n_150), .SE (A_Vote[0]), .Q (A_Vote[0]));
  SDFFRHQX1 \B_Vote_reg[0] (.RN (n_153), .CK (clk), .D (n_119), .SI
       (n_148), .SE (B_Vote[0]), .Q (B_Vote[0]));
  SDFFRHQX1 \vote_count_reg[4] (.RN (n_153), .CK (clk), .D
       (vote_count[4]), .SI (n_80), .SE (n_121), .Q (vote_count[4]));
  OAI211X1 g3028__1666(.A0 (C_Vote[4]), .A1 (n_50), .B0 (n_60), .C0
       (n_145), .Y (n_118));
  OAI211X1 g3060__7410(.A0 (B_Vote[3]), .A1 (n_26), .B0 (n_37), .C0
       (n_119), .Y (n_117));
  OAI211X1 g3061__6417(.A0 (A_Vote[3]), .A1 (n_29), .B0 (n_35), .C0
       (n_120), .Y (n_116));
  OAI211X1 g3026__5477(.A0 (A_Vote[4]), .A1 (n_56), .B0 (n_62), .C0
       (n_120), .Y (n_115));
  OAI211X1 g3027__2398(.A0 (B_Vote[4]), .A1 (n_49), .B0 (n_61), .C0
       (n_119), .Y (n_114));
  OAI211X1 g3065__6260(.A0 (C_Vote[3]), .A1 (n_28), .B0 (n_36), .C0
       (n_145), .Y (n_112));
  OAI211X1 g3078__4319(.A0 (C_Vote[0]), .A1 (C_Vote[1]), .B0 (n_4), .C0
       (n_145), .Y (n_111));
  OAI211X1 g3079__8428(.A0 (C_Vote[2]), .A1 (n_12), .B0 (n_18), .C0
       (n_145), .Y (n_110));
  NAND2X1 g3009__5526(.A (C_Vote[6]), .B (n_109), .Y (n_138));
  NAND2X1 g3008__6783(.A (A_Vote[6]), .B (n_108), .Y (n_142));
  OAI211X1 g3084__3680(.A0 (A_Vote[2]), .A1 (n_11), .B0 (n_17), .C0
       (n_120), .Y (n_107));
  OAI211X1 g3082__1617(.A0 (B_Vote[0]), .A1 (B_Vote[1]), .B0 (n_2), .C0
       (n_119), .Y (n_106));
  OAI211X1 g3013__2802(.A0 (C_Vote[5]), .A1 (n_86), .B0 (n_93), .C0
       (n_145), .Y (n_105));
  OAI211X1 g3083__1705(.A0 (B_Vote[2]), .A1 (n_13), .B0 (n_19), .C0
       (n_119), .Y (n_104));
  OAI211X1 g3011__5122(.A0 (A_Vote[5]), .A1 (n_85), .B0 (n_92), .C0
       (n_120), .Y (n_103));
  OAI211X1 g3081__8246(.A0 (A_Vote[0]), .A1 (A_Vote[1]), .B0 (n_5), .C0
       (n_120), .Y (n_102));
  OAI211X1 g3012__7098(.A0 (B_Vote[5]), .A1 (n_87), .B0 (n_94), .C0
       (n_119), .Y (n_101));
  SDFFRHQX1 voted_reg(.RN (n_153), .CK (clk), .D (n_71), .SI (voted),
       .SE (n_76), .Q (voted));
  NAND2X1 g3010__6131(.A (B_Vote[6]), .B (n_100), .Y (n_140));
  DFFRHQX1 \state_reg[0] (.RN (n_153), .CK (clk), .D (n_88), .Q
       (state[0]));
  SDFFRHQX1 \vote_count_reg[0] (.RN (n_153), .CK (clk), .D
       (vote_count[0]), .SI (n_79), .SE (n_121), .Q (vote_count[0]));
  OAI32X1 g3063__1881(.A0 (n_96), .A1 (n_98), .A2 (n_68), .B0 (n_67),
       .B1 (n_121), .Y (n_99));
  OAI32X1 g3064__5115(.A0 (n_96), .A1 (n_98), .A2 (n_69), .B0 (n_10),
       .B1 (n_121), .Y (n_97));
  OAI32X1 g3075__7482(.A0 (vote_count[7]), .A1 (n_72), .A2 (n_90), .B0
       (n_38), .B1 (n_73), .Y (n_95));
  DFFRHQX1 \state_reg[1] (.RN (n_153), .CK (clk), .D (n_84), .Q
       (state[1]));
  INVX1 g3014(.A (n_94), .Y (n_100));
  INVX1 g3015(.A (n_93), .Y (n_109));
  INVX1 g3016(.A (n_92), .Y (n_108));
  OAI31X1 g3087__4733(.A0 (vote_count[5]), .A1 (n_42), .A2 (n_90), .B0
       (n_74), .Y (n_91));
  OAI32X1 g3090__6161(.A0 (vote_count[3]), .A1 (n_65), .A2 (n_90), .B0
       (n_14), .B1 (n_66), .Y (n_89));
  NAND3BXL g3073__9315(.AN (n_83), .B (n_70), .C (n_78), .Y (n_88));
  INVX1 g3080(.A (n_145), .Y (n_133));
  NAND2X1 g3025__9945(.A (B_Vote[5]), .B (n_87), .Y (n_94));
  NAND2X1 g3024__2883(.A (C_Vote[5]), .B (n_86), .Y (n_93));
  NAND2X1 g3023__2346(.A (A_Vote[5]), .B (n_85), .Y (n_92));
  AOI21X1 g3085__1666(.A0 (n_20), .A1 (n_55), .B0 (n_57), .Y (n_145));
  NAND3BXL g3089__7410(.AN (n_83), .B (n_47), .C (n_75), .Y (n_84));
  AOI32X1 g3088__6417(.A0 (n_81), .A1 (n_51), .A2 (n_44), .B0
       (vote_count[6]), .B1 (n_52), .Y (n_82));
  OAI31X1 g3086__5477(.A0 (vote_count[4]), .A1 (n_31), .A2 (n_90), .B0
       (n_63), .Y (n_80));
  INVX1 g3092(.A (n_150), .Y (n_120));
  INVX1 g3091(.A (n_148), .Y (n_119));
  MXI2XL g3102__2398(.A (n_90), .B (n_78), .S0 (vote_count[0]), .Y
       (n_79));
  NAND2X1 g3099__5107(.A (n_53), .B (n_77), .Y (n_150));
  NAND2X1 g3098__6260(.A (n_54), .B (n_77), .Y (n_148));
  OA21X1 g3106__4319(.A0 (n_46), .A1 (n_24), .B0 (n_75), .Y (n_76));
  OAI2BB1X1 g3104__8428(.A0N (n_43), .A1N (n_78), .B0 (vote_count[5]),
       .Y (n_74));
  AOI21X1 g3103__5526(.A0 (n_72), .A1 (n_71), .B0 (n_64), .Y (n_73));
  DFFRHQX1 limit_exceeded_reg(.RN (n_153), .CK (clk), .D (n_59), .Q
       (limit_exceeded));
  AOI221X1 g3105__6783(.A0 (n_6), .A1 (ballot_signal), .B0 (n_3), .B1
       (n_45), .C0 (n_58), .Y (n_70));
  XNOR2X1 g3101__3680(.A (vote_count[2]), .B (n_41), .Y (n_69));
  MX2XL g3100__1617(.A (vote_count[1]), .B (n_67), .S0 (n_39), .Y
       (n_68));
  INVX1 g3111(.A (n_121), .Y (n_98));
  AOI21X1 g3119__2802(.A0 (n_65), .A1 (n_71), .B0 (n_64), .Y (n_66));
  OAI2BB1X1 g3093__1705(.A0N (n_32), .A1N (n_78), .B0 (vote_count[4]),
       .Y (n_63));
  INVX1 g3030(.A (n_62), .Y (n_85));
  INVX1 g3031(.A (n_61), .Y (n_87));
  INVX1 g3029(.A (n_60), .Y (n_86));
  OR2XL g3112__5122(.A (limit_exceeded), .B (n_58), .Y (n_59));
  OR2XL g3113__8246(.A (n_57), .B (n_40), .Y (n_75));
  NAND2X1 g3049__7098(.A (A_Vote[4]), .B (n_56), .Y (n_62));
  NAND2X1 g3115__6131(.A (n_57), .B (n_30), .Y (n_121));
  OAI21X1 g3118__1881(.A0 (n_54), .A1 (n_53), .B0 (n_48), .Y (n_55));
  OAI21X1 g3117__5115(.A0 (n_51), .A1 (n_96), .B0 (n_78), .Y (n_52));
  NAND2X1 g3066__7482(.A (C_Vote[4]), .B (n_50), .Y (n_60));
  NAND2X1 g3067__4733(.A (B_Vote[4]), .B (n_49), .Y (n_61));
  NOR2X1 g3114__6161(.A (n_48), .B (n_57), .Y (n_77));
  OAI21X1 g3116__9315(.A0 (n_46), .A1 (n_45), .B0 (n_22), .Y (n_47));
  INVX1 g3139(.A (n_78), .Y (n_64));
  INVX1 g3138(.A (n_44), .Y (n_90));
  NAND2XL g3140__9945(.A (n_42), .B (n_71), .Y (n_43));
  NAND2X1 g3150__2883(.A (vote_count[6]), .B (n_51), .Y (n_72));
  DFFRHQX1 \buzzer_count_reg[1] (.RN (n_153), .CK (clk), .D (n_33), .Q
       (buzzer_count[1]));
  NOR2X1 g3149__2346(.A (n_9), .B (n_40), .Y (n_41));
  NAND2BXL g3152__1666(.AN (n_40), .B (vote_count[0]), .Y (n_39));
  OAI211X1 g3151__7410(.A0 (n_27), .A1 (n_16), .B0 (n_81), .C0 (n_38),
       .Y (n_48));
  NOR2XL g3148__6417(.A (n_34), .B (n_96), .Y (n_58));
  DFFRHQX1 \buzzer_count_reg[0] (.RN (n_153), .CK (clk), .D (n_23), .Q
       (buzzer_count[0]));
  INVX1 g3068(.A (n_37), .Y (n_49));
  INVX1 g3070(.A (n_36), .Y (n_50));
  NOR2X1 g3155__5477(.A (n_96), .B (n_40), .Y (n_44));
  INVX1 g3069(.A (n_35), .Y (n_56));
  NAND2XL g3154__2398(.A (n_34), .B (n_71), .Y (n_57));
  NAND2X1 g3156__5107(.A (n_71), .B (n_40), .Y (n_78));
  XNOR2X1 g3120__6260(.A (buzzer_count[1]), .B (n_21), .Y (n_33));
  NAND2XL g3157__4319(.A (n_31), .B (n_71), .Y (n_32));
  SDFFRHQX1 \B_Count_reg[2] (.RN (n_153), .CK (clk), .D (B_Vote[2]),
       .SI (B_Count[2]), .SE (n_30), .Q (B_Count[2]));
  SDFFRHQX1 \C_Count_reg[1] (.RN (n_153), .CK (clk), .D (C_Vote[1]),
       .SI (C_Count[1]), .SE (n_30), .Q (C_Count[1]));
  NAND2X1 g3107__8428(.A (A_Vote[3]), .B (n_29), .Y (n_35));
  SDFFRHQX1 \C_Count_reg[0] (.RN (n_153), .CK (clk), .D (C_Vote[0]),
       .SI (C_Count[0]), .SE (n_30), .Q (C_Count[0]));
  SDFFRHQX1 \B_Count_reg[6] (.RN (n_153), .CK (clk), .D (B_Vote[6]),
       .SI (B_Count[6]), .SE (n_30), .Q (B_Count[6]));
  NAND2X1 g3097__5526(.A (C_Vote[3]), .B (n_28), .Y (n_36));
  SDFFRHQX1 \A_Count_reg[1] (.RN (n_153), .CK (clk), .D (A_Vote[1]),
       .SI (A_Count[1]), .SE (n_30), .Q (A_Count[1]));
  SDFFRHQX1 \A_Count_reg[0] (.RN (n_153), .CK (clk), .D (A_Vote[0]),
       .SI (A_Count[0]), .SE (n_30), .Q (A_Count[0]));
  SDFFRHQX1 \B_Count_reg[3] (.RN (n_153), .CK (clk), .D (B_Vote[3]),
       .SI (B_Count[3]), .SE (n_30), .Q (B_Count[3]));
  NAND2BX1 g3158__6783(.AN (n_31), .B (vote_count[4]), .Y (n_42));
  SDFFRHQX1 \A_Count_reg[3] (.RN (n_153), .CK (clk), .D (A_Vote[3]),
       .SI (A_Count[3]), .SE (n_30), .Q (A_Count[3]));
  SDFFRHQX1 \B_Count_reg[5] (.RN (n_153), .CK (clk), .D (B_Vote[5]),
       .SI (B_Count[5]), .SE (n_30), .Q (B_Count[5]));
  NOR2X1 g3164__3680(.A (n_27), .B (n_31), .Y (n_51));
  NAND2X1 g3096__1617(.A (B_Vote[3]), .B (n_26), .Y (n_37));
  SDFFRHQX1 \B_Count_reg[0] (.RN (n_153), .CK (clk), .D (B_Vote[0]),
       .SI (B_Count[0]), .SE (n_30), .Q (B_Count[0]));
  SDFFRHQX1 \B_Count_reg[1] (.RN (n_153), .CK (clk), .D (B_Vote[1]),
       .SI (B_Count[1]), .SE (n_30), .Q (B_Count[1]));
  SDFFRHQX1 \A_Count_reg[2] (.RN (n_153), .CK (clk), .D (A_Vote[2]),
       .SI (A_Count[2]), .SE (n_30), .Q (A_Count[2]));
  SDFFRHQX1 \C_Count_reg[4] (.RN (n_153), .CK (clk), .D (C_Vote[4]),
       .SI (C_Count[4]), .SE (n_30), .Q (C_Count[4]));
  SDFFRHQX1 \C_Count_reg[3] (.RN (n_153), .CK (clk), .D (C_Vote[3]),
       .SI (C_Count[3]), .SE (n_30), .Q (C_Count[3]));
  SDFFRHQX1 \C_Count_reg[5] (.RN (n_153), .CK (clk), .D (C_Vote[5]),
       .SI (C_Count[5]), .SE (n_30), .Q (C_Count[5]));
  SDFFRHQX1 \A_Count_reg[7] (.RN (n_153), .CK (clk), .D (A_Vote[7]),
       .SI (A_Count[7]), .SE (n_30), .Q (A_Count[7]));
  SDFFRHQX1 \B_Count_reg[4] (.RN (n_153), .CK (clk), .D (B_Vote[4]),
       .SI (B_Count[4]), .SE (n_30), .Q (B_Count[4]));
  SDFFRHQX1 \C_Count_reg[7] (.RN (n_153), .CK (clk), .D (C_Vote[7]),
       .SI (C_Count[7]), .SE (n_30), .Q (C_Count[7]));
  SDFFRHQX1 \A_Count_reg[5] (.RN (n_153), .CK (clk), .D (A_Vote[5]),
       .SI (A_Count[5]), .SE (n_30), .Q (A_Count[5]));
  SDFFRHQX1 \C_Count_reg[2] (.RN (n_153), .CK (clk), .D (C_Vote[2]),
       .SI (C_Count[2]), .SE (n_30), .Q (C_Count[2]));
  SDFFRHQX1 \A_Count_reg[6] (.RN (n_153), .CK (clk), .D (A_Vote[6]),
       .SI (A_Count[6]), .SE (n_30), .Q (A_Count[6]));
  SDFFRHQX1 \C_Count_reg[6] (.RN (n_153), .CK (clk), .D (C_Vote[6]),
       .SI (C_Count[6]), .SE (n_30), .Q (C_Count[6]));
  SDFFRHQX1 \A_Count_reg[4] (.RN (n_153), .CK (clk), .D (A_Vote[4]),
       .SI (A_Count[4]), .SE (n_30), .Q (A_Count[4]));
  SDFFRHQX1 \B_Count_reg[7] (.RN (n_153), .CK (clk), .D (B_Vote[7]),
       .SI (B_Count[7]), .SE (n_30), .Q (B_Count[7]));
  NAND3BXL g3162__2802(.AN (n_25), .B (vote_count[7]), .C (n_15), .Y
       (n_34));
  NOR3X1 g3163__1705(.A (n_7), .B (n_25), .C (n_24), .Y (n_45));
  OA21X1 g3172__5122(.A0 (buzzer_count[0]), .A1 (n_22), .B0 (n_21), .Y
       (n_23));
  NOR3BX1 g3166__8246(.AN (n_20), .B (n_53), .C (n_54), .Y (n_40));
  INVX1 g3108(.A (n_19), .Y (n_26));
  INVX1 g3109(.A (n_18), .Y (n_28));
  INVX1 g3110(.A (n_17), .Y (n_29));
  NOR2X1 g3171__7098(.A (vote_count[3]), .B (n_15), .Y (n_16));
  SDFFRHQX1 buzzer_output_reg(.RN (n_153), .CK (clk), .D (n_46), .SI
       (buzzer_output), .SE (n_24), .Q (buzzer_output));
  OR2X1 g3170__6131(.A (n_14), .B (n_65), .Y (n_31));
  NAND2X1 g3176__1881(.A (buzzer_count[0]), .B (n_22), .Y (n_21));
  NAND2X1 g3160__5115(.A (B_Vote[2]), .B (n_13), .Y (n_19));
  NAND2X1 g3161__7482(.A (C_Vote[2]), .B (n_12), .Y (n_18));
  NAND2X1 g3165__4733(.A (A_Vote[2]), .B (n_11), .Y (n_17));
  NOR2X1 g3173__6161(.A (n_8), .B (show_result), .Y (n_83));
  NAND2X1 g3174__9315(.A (n_10), .B (n_9), .Y (n_15));
  OR2X2 g3177__9945(.A (n_8), .B (n_0), .Y (n_30));
  OR4X1 g3178__2883(.A (vote_count[2]), .B (vote_count[0]), .C (n_67),
       .D (n_38), .Y (n_7));
  NAND3BXL g3180__2346(.AN (n_27), .B (vote_count[6]), .C
       (vote_count[3]), .Y (n_25));
  NAND2X1 g3181__1666(.A (C_Push), .B (n_1), .Y (n_20));
  OR2X1 g3175__7410(.A (n_10), .B (n_9), .Y (n_65));
  NOR3X1 g3179__6417(.A (voted), .B (state[1]), .C (state[0]), .Y
       (n_6));
  INVX1 g3167(.A (n_5), .Y (n_11));
  INVX1 g3168(.A (n_4), .Y (n_12));
  NOR3BX1 g3182__5477(.AN (B_Push), .B (A_Push), .C (C_Push), .Y
       (n_54));
  INVX1 g3190(.A (n_46), .Y (n_3));
  INVX1 g3169(.A (n_2), .Y (n_13));
  NOR3BX1 g3183__2398(.AN (A_Push), .B (B_Push), .C (C_Push), .Y
       (n_53));
  INVX1 g3184(.A (n_24), .Y (n_22));
  INVX1 g3191(.A (n_71), .Y (n_96));
  NOR2X1 g3185__5107(.A (B_Push), .B (A_Push), .Y (n_1));
  NAND2X1 g3186__6260(.A (state[1]), .B (state[0]), .Y (n_8));
  NAND2X1 g3187__4319(.A (A_Vote[1]), .B (A_Vote[0]), .Y (n_5));
  NAND2X1 g3195__8428(.A (buzzer_count[1]), .B (buzzer_count[0]), .Y
       (n_46));
  NAND2BX1 g3189__5526(.AN (state[0]), .B (state[1]), .Y (n_24));
  NAND2X1 g3188__6783(.A (C_Vote[1]), .B (C_Vote[0]), .Y (n_4));
  NAND2X1 g3194__3680(.A (B_Vote[1]), .B (B_Vote[0]), .Y (n_2));
  NAND2X1 g3192__1617(.A (vote_count[5]), .B (vote_count[4]), .Y
       (n_27));
  NAND2X1 g3193__2802(.A (vote_count[1]), .B (vote_count[0]), .Y (n_9));
  NOR2BX1 g3196__1705(.AN (state[0]), .B (state[1]), .Y (n_71));
  INVX1 g3201(.A (show_result), .Y (n_0));
  INVX1 g3199(.A (vote_count[7]), .Y (n_38));
  INVX1 g3203(.A (vote_count[3]), .Y (n_14));
  INVXL g3200(.A (reset), .Y (n_153));
  OAI21X1 g2(.A0 (n_81), .A1 (n_121), .B0 (n_82), .Y (n_161));
  DFFRX1 \vote_count_reg[6] (.RN (n_153), .CK (clk), .D (n_161), .Q
       (vote_count[6]), .QN (n_81));
  DFFRX1 \vote_count_reg[2] (.RN (n_153), .CK (clk), .D (n_97), .Q
       (vote_count[2]), .QN (n_10));
  DFFRX1 \vote_count_reg[1] (.RN (n_153), .CK (clk), .D (n_99), .Q
       (vote_count[1]), .QN (n_67));
endmodule

